apiVersion: v1
kind: Service
metadata:
  name: time-toronto
spec:
  type: NodePort
  selector:
    app: project2-app
  ports:
    - port: 3030
      targetPort: 3030
      nodePort: 32727
  type: LoadBalancer